### ISSUE TITLE
skip adapter removal step

### ISSUE THREAD

**Issue by LeandroRitter** [NBISweden/aMeta#105]
I got a few requests on adding an option to skip adapter removal step because users typically have fastq-files with adapters already removed. I tried to persuade them to still run the adapter removal and not skip it because from my experience there are always adapter left overs present and removing adapters one more time does not hurt but is only beneficial. I added this to FAQ in the README, but we should think about adding the skipping adapter removal option anyway.

**Comment by ZoePochon** [comment]
I think that is a good idea. I was also wondering, what happens in our case when we try to remove adapters on Fastq files with already merged reads ?

**Comment by LeandroRitter** [comment]
@ZoePochon nothing should happen to the adapter-free merged reads if you run a Cutadapt one more time, the output should be identical to the input. Generally I see quite a lot of adapter traces left even after people say they did adapter removal. Therefore, my recommendation would be not to be afraid to run adapter removal many times with different tools. One more time does not hurt but can only be beneficial in case there are adapter traces left, this is what is also written in the FAQ section here https://github.com/NBISweden/aMeta

**Comment by LeandroRitter** [comment]
I close the issue since it seems to be unnecessary to skip adapter removal
