### ISSUE TITLE
MapDamage is only applied to pathogens

### ISSUE THREAD

**Issue by ZoePochon** [NBISweden/aMeta#120]
As in the title, the rule MapDamage is only applied to pathogens. This is less problematic because it is a side branch of the pipeline for fast analysis, but if we want the pipeline to be used for metagenomics of all samples we need to be more inclusive here.

**Comment by LeandroRitter** [comment]
Should not be any more with the new commit https://github.com/NBISweden/aMeta/pull/123. Otherwise, @ZoePochon if you notice that it does not work as expected, feel free to reopen the issue
