### ISSUE TITLE
Deamination takes too much time for large samples

### ISSUE THREAD

**Issue by ZoePochon** [NBISweden/aMeta#121]
If I am not mistaken, the Deamination rule solely creates a deamination plot. However, it can take more than 24h to run for large samples.
I think we need to reintroduce the option "number" here in the pmdtools command of this rule.

Suggestion:
--number 2000000

Should be sufficient to create a smooth plot according to colleagues.

**Comment by LeandroRitter** [comment]
I close it since the issue was fixed in the previous PR
