### ISSUE TITLE
Error: duplicates in sam-header when running Bowtie2 on full NT

### ISSUE THREAD

**Issue by LeandroRitter** [NBISweden/aMeta#122]
When following up KrakenUniq hits with Bowtie2 on full NT and not on the PathoGenome (default), there is an error originating from duplicate records in the sam-header. One needs to grep the duplicates, clean the header, and replace it in the sam-file. I have the codes that do it, and will push a commit that fixes this issue soon.

**Comment by percyfal** [comment]
Re PR #123 ; now I see what you were doing, should have read this first!

**Comment by LeandroRitter** [comment]
fixed with new commit https://github.com/NBISweden/aMeta/pull/123
