### ISSUE TITLE
Authentication plots pdf files are too heavy

### ISSUE THREAD

**Issue by ZoePochon** [NBISweden/aMeta#127]
The authentication plots pdf files are just so heavy that they make xquartz or slack fail when trying to open them. 
It makes them not easy to share. Maybe we could have a jpg format as well that would require less space ? I suppose they take up quite some space as well.

**Comment by LeandroRitter** [comment]
I close it since the issue was fixed in the previous PR. A PNG converter was added so the aMeta output can now be viewed as a png image
