### ISSUE TITLE
Usage of default MALT parameters 

### ISSUE THREAD

**Issue by Thijessen** [NBISweden/aMeta#129]
Currently the workflow is set up to run MALT with default parameters; whereas during testing parameters were changed to match those used in HOPS, etc. Since this may cause results to differ, this should be examined more closely. It could be that the parameters used in HOPS are better to use.

It may be better for the MALT rule have parameters explicitly stated, or is there a way to change or submit new parameters through the config file? This would allow for easier testing of different parameters.

**Comment by LeandroRitter** [comment]
I agree, the default Malt parameters do not make much sense to me so we better stick to the HOPs settings here https://github.com/rhuebler/HOPS/blob/external/Resources/HOPS_Config.txt. Solved by PR https://github.com/NBISweden/aMeta/pull/130
