### ISSUE TITLE
Add pysam to the workflow/envs/mapdamage.yaml

### ISSUE THREAD

**Issue by ZoePochon** [NBISweden/aMeta#132]
As MinLuke reported in issue #131, newly created conda environments don't work on the mapDamage step because they don't find pysam. 

A quick fix is to add pysam in the workflow/envs/mapdamage.yaml like this:

channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - htslib<1.15.1
  - mapdamage2
  - htslib<1.15.1
  - parallel
  - samtools
  - pysam

worked for him and for me

**Comment by jfy133** [comment]
Can confirm the issue!

**Comment by jfy133** [comment]
(testing the workaround)

**Comment by LeandroRitter** [comment]
I close it since the issue was fixed in the previous PR
