### ISSUE TITLE
MaltExtract has trouble finding ncbi.map and ncbi.tre files

### ISSUE THREAD

**Issue by Thijessen** [NBISweden/aMeta#133]
MaltExtract has trouble finding ncbi.map and ncbi.tre files so it downloads them as needed. The "-r {params.ncbi_db}" flag needs to be added to the MaltExtract rule. It might also be useful to suggest that the ncbi.map and ncbi.tre files be downloaded stored in the resources/ncbi_db folder.

**Comment by LeandroRitter** [comment]
I close it since the issue was fixed in the previous PR
