### ISSUE TITLE
add --large-index to the Bowtie2_Index rule

### ISSUE THREAD

**Issue by LeandroRitter** [NBISweden/aMeta#142]
Interestingly, the bowtie2 index building command line does not have "--large-index":

`bowtie2-build-l --threads {threads} {input.ref} {input.ref} > {log} 2>&1`

so one user reported that it bowtie2-build-l builds a small index *.b2t while *.bt2l index is expected. So we should just replace this line with:

`bowtie2-build --large-index --threads {threads} {input.ref} {input.ref} > {log} 2>&1`

in the aMeta/workflow/rules/align.smk

**Comment by ZoePochon** [comment]
This might explain why it never worked for me on Dardel to recreate the database no?

**Comment by percyfal** [comment]
Do we always want to enforce large index?

**Comment by percyfal** [comment]
Actually, running `bowtie2-build-l` gives the following message:

```
*** Warning ***
'bowtie2-build-l' was run directly.  It is recommended that you run the wrapper script 'bowtie2-build' instead.
```

One should therefore use the `bowtie2-build --large-index` command.

**Comment by LeandroRitter** [comment]
Oh, ok, then then we should still change it to `bowtie2-build --large-index`! Even though this unlikely was the cause of the problem for the user when a small index built instead of a large index.

**Comment by LeandroRitter** [comment]
Fixed in the latest PR
