### ISSUE TITLE
The png file for authentication plots doesn't render well on mac

### ISSUE THREAD

**Issue by ZoePochon** [NBISweden/aMeta#151]
![image](https://github.com/NBISweden/aMeta/assets/78050804/88e7aa58-b791-4a5b-bb77-75e79a791659)
Left png file, right pdf file.

**Comment by LeandroRitter** [comment]
`convert` has a `background` argument. I believe adding `-background white` to the `convert` command at the very end of authentic.R should fix the issue.

**Comment by LeandroRitter** [comment]
@ZoePochon I think I fixed it in the latest PR, however feel free to reopen if you see problems with rendering on Mac again
