### ISSUE TITLE
Python syntax of Malt-build script doesn't work with Python 3.12.1

### ISSUE THREAD

**Issue by ZoePochon** [NBISweden/aMeta#155]
I was helping debug with @npsonis and it seems that the new python version 3.12.1 fails to read the syntax of one of the command in the malt-build.py script. 

This is the command:
regex = re.compile("version (?P<major>\d+)\.(?P<minor>\d+)")
And this is the warning but the malt-build eventually fails:
<stdin>:1: SyntaxWarning: invalid escape sequence '\d'

We tested it on the command line when activating python 3.12.1 and got the same error but we didn't get the error when running it with python 3.11.4. So it might be some python update that makes this syntax not readable anymore?

**Comment by peterjc** [comment]
That breaks on Python 3.10.12 and Python 3.11.6 too:

```
$ python -c 'import re; re.compile("version (?P\d+).(?P\d+)")'
...
re.error: unknown extension ?P\d at position 9
```

The actual line from the script is different https://github.com/NBISweden/aMeta/blame/main/workflow/scripts/malt-build.py

This does work on Python 3.10.12 and 3.11.6:

```
$ python -c 'import re; re.compile("version (?P<major>\d+)\.(?P<minor>\d+)")'
```


I don't have a Python 3.13 handy to try this on :(

According to https://docs.python.org/3/library/re.html the ``(?P<name>...)`` functionality did change in Python 3.12:

> Changed in version 3.12: In [bytes](https://docs.python.org/3/library/stdtypes.html#bytes) patterns, group name can only contain bytes in the ASCII range (b'\x00'-b'\x7f').

The names (major and minor) do look to be within the ASCII range. That is probably unrelated.

**Comment by peterjc** [comment]
I lack the context to say - as I recall I ran into a similar issue and looked at this while trying to debug that.

**Comment by ZoePochon** [comment]
Doesn't snakemake break because of warnings as well? At least this has been my understanding so far working with aMeta

**Comment by peterjc** [comment]
Could be - that was my guess, something in strict mode could be upgrading the "harmless" warning into an error.

Anyway, the regex change is simple and seems low risk.

**Comment by LeandroRitter** [comment]
At least the testrun does not fail for me. If the reason for failure was the python syntax upgrade, the testrun should also fail. Do you guys see that it fails with the same error if you

```
cd aMeta/.test
rm -rf results
./runtest.sh -j 1
```

**Comment by ZoePochon** [comment]
I changed my aMeta conda environment to turn around the error quite some time ago. 
However, I think the error might escape the test run somehow since Markella encountered it on real data to my understanding (and she most probably did the test run first as she was setting up the pipeline)

**Comment by LeandroRitter** [comment]
@ZoePochon @peterjc @percyfal I installed aMeta from scratch at my laptop and an HPC, and ran both the test and real data without errors. No errors on the Malt database building step. I am using python 3.10.12 , and I tested it with python 3.10.8 as well with the same result: no errors. Nevertheless I believe (and @percyfal seems to agree, right?) that if you simply replace this line

`regex = re.compile("version (?P<major>\d+)\.(?P<minor>\d+)")`

with this line

`regex =  re.compile(r'version (?P<major>\d+)\.(?P<minor>\d+)')`

in the `aMeta/workflow/scripts/malt-build.py`, this should fix the issue even for the newer python versions. I am preparing a PR with this modification. So the issue should be fixed centrally soon.

**Comment by ZoePochon** [comment]
Sounds good!

**Comment by LeandroRitter** [comment]
@peterjc forgot to say: huge thanks for helping us with debugging, your input was very valuable! As far as I can see, python does not throw any warning or error at

`python -c 'import re; re.compile(r"version (?P<major>\d+)\.(?P<minor>\d+)")'`

no matter what python version is used, I tested several versions from 3.6 to 3.12.

**Comment by LeandroRitter** [comment]
Fixed in the latest PR
