### ISSUE TITLE
krakendb/taxDB and krakendb/taxDB.

### ISSUE THREAD

**Issue by CJJ8848** [NBISweden/aMeta#169]
Hi aMeta team! 

Thanks for providing such a great ancient metagenome pipe. I found a very minor issue when downloading the krakendb from https://doi.org/10.17044/scilifelab.20518251. After wget, there was a 'taxDB.' file and when I run KrakenUniq step, the error log showed: 

krakenuniq --preload --db /path/to/resources/krakendb --fastq-input results/CUTADAPT_ADAPTER_TRIMMING/PL0245.trimmed.fastq.gz --threads 8 --output results/KRAKENUNIQ/PL0245/sequences.krakenuniq --report-file results/KRAKENUNIQ/PL0245/krakenuniq.output --gzip-compressed --only-classified-out
NOTE: No need to use --gzip-compressed or --bzip2-compressed anymore, format is detected automatically.
NOTE: No need to use --fasta-input or --fastq-input anymore, format is detected automatically.
Taxonomy database not at  /path/to/resources/krakendb/taxDB - creating it .../ path/to/tools/aMeta/resources/krakendb/taxonomy/nodes.dmp does not exist! at  /path/to/tools/aMeta/.snakemake/conda/247838bd5e853115f218d1a062fdc248_/bin/krakenuniq line 209.
 
Krakenuniq works after I changed the name of 'krakendb/taxDB.' to 'krakendb/taxDB'

Guess it could be a mismatch between the downloaded file name and the real name recognized by Krakenuniq code. Hope it would help if any of you has the same problem. Thanks!

jiajun

**Comment by LeandroRitter** [comment]
Hi @CJJ8848, thanks a lot for reporting! Yes, we are aware of this issue. Indeed, depending on what environment you have (Win/Mac/Linux) and program you use, as well as whether you download the whole DB or separate files, the file names might change a bit. For example, "taxDB" may become "taxDB." or "taxdb", while KrakenUniq will specifically search for "taxDB" and throw an error of the file names does not match. This is hard to fix, but we should definitely add a comment about it to DB downloading section on github and perhaps a FAQ section about it

**Comment by LeandroRitter** [comment]
Addressed in latest PR
