### ISSUE TITLE
Remove trailing sam files

### ISSUE THREAD

**Issue by percyfal** [NBISweden/aMeta#83]
Rule Breadth_Of_Coverage generates both bam and sam output with redundant information AFAICT. Since sam format is not very space efficient, this output should be removed at some stage.

**Comment by LeandroRitter** [comment]
As far as I can see, the Breadth_Of_Coverage rue does not keep the sam-files anymore, has been fixed with the "temporary" keyword as sam=temporary("results/AUTHENTICATION/{sample}/{taxid}/{taxid}.sam"). Feel free to reopen if this issue still exists
