### ISSUE TITLE
Warning regarding path for log file

### ISSUE THREAD

**Issue by ZoePochon** [NBISweden/aMeta#85]
It seems that this command in the rule Bowtie2_Index in align.smk
log:
        f"logs/BOWTIE2_BUILD/{config['bowtie2_patho_db']}.log",

generates always the same warning when running the pipeline: 
File path logs/BOWTIE2_BUILD//proj/nobackup/metagenomics/databases/PathoGenome/library.pathogen.fna.log contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
File path logs/BOWTIE2_BUILD//proj/nobackup/metagenomics/databases/PathoGenome/library.pathogen.fna.log contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.

This is what I have in my config file:
bowtie2_patho_db: /proj/nobackup/metagenomics/databases/PathoGenome/library.pathogen.fna

This would be easily fixable by getting rid of the "/" in the command itself, but I also think that the generated path is just too long for a log file no ?

**Comment by FreysSteinhagen** [comment]
I seem to encounter the same Problem. Did you fix it manually in the align.smk?

**Comment by ZoePochon** [comment]
Hi ! 
Yes so far I just changed it myself in the align.smk as it was just a warning:

log:
        "logs/BOWTIE2_INDEX/BOWTIE2_INDEX.log",

I'm gonna ask for a merge about this.

**Comment by ZoePochon** [comment]
Warning fixed with the merge.
