### ISSUE TITLE
Impossible to give more threads to the rule "KrakenUniq2Krona"

### ISSUE THREAD

**Issue by ZoePochon** [NBISweden/aMeta#86]
So I have noticed that whatever I change in the config file, I cannot allocate more cpu than 1 to the rule "KrakenUniq2Krona". I suspect that this is because their is another rule called KrakenUniq that I encounter this problem. Not very sure why otherwise cause it's the only rule for which I have this problem.

**Comment by clami66** [comment]
Pull request #87 makes it not necessary to request a full node for this rule (should run on a single core now, hopefully). So I will close this issue
