### ISSUE TITLE
filter_krakenuniq, krakenuniq2krona, krakenuniq_abundance_matrix scripts overlap

### ISSUE THREAD

**Issue by clami66** [NBISweden/aMeta#88]
All these scripts perform a filtering step on `krakenuniq.output` where hits are filtered by breadth/depth of coverage, the parameters are the same. It would be good to isolate this part of the processing to a separate, common script for better maintainability

**Comment by percyfal** [comment]
Indeed. And here is where I would push for the CLI-based python package setup which would allow for 
- separate tests with e.g. pytest
- making the scripts truly standalone and accessible with e.g. aMeta-krakenfilter

**Comment by ZoePochon** [comment]
Yes, we were thinking the same with Emrah. It would make the dag more unterstandable if there is an inbetween rule for filtering and this three rules come after.
